- src/pages/editReservationInfo copy/index.tsx
- src/pages/editReservationInfo/index.tsx
- src/pages/myPage/index.tsx
- src/pages/mypage copy/index.tsx
- src/pages/payment copy/index.tsx
- src/pages/payment/index.tsx
- src/pages/point copy/index.tsx
- src/pages/point/index.tsx
- src/pages/profile copy/index.tsx
- src/pages/profile/index.tsx
- src/pages/purchase copy/index.tsx
- src/pages/purchase/index.tsx
- src/pages/purchaseHistory copy/index.tsx
- src/pages/purchaseHistory/index.tsx
- src/pages/reservationComplete/index.tsx
- src/pages/salesHistory copy/index.tsx
- src/pages/salesHistory/index.tsx
- src/pages/serviceCenter/index.tsx
- src/pages/terms copy/index.tsx
- src/pages/terms/index.tsx
- src/pages/transactionHistory copy/index.tsx
- src/pages/transactionHistory/index.tsx
- src/pages/withdraw/index.tsx
- src/pages/yanabadaPayment copy/index.tsx
- src/pages/yanabadaPayment/index.tsx
#4
- 마이페이지 파트 페이지 구성
- 구매 파트 페이지 구성
close #04
> Docs: 마이페이지, 구매 파트 페이지 구성

- src/assets/icons/checkbox_Check.svg
- src/assets/icons/checkbox_rightArrow.svg
- src/components/input/Checkbox/AllConsentCheckbox.tsx
- src/components/input/Checkbox/IndividualConsentCheckbox.tsx
- src/components/input/Checkbox/allConsentCheckbox.style.ts
- src/components/input/Checkbox/index.tsx
- src/components/input/Checkbox/individualConsentCheckbox.style.ts
#7 
`<Checkbox variant="all" content="" />`
`<Checkbox variant="individual" title="" content="" hasMoreContent=true onLoadMoreContent={} />`
굿!
- 폴더 구조나 타입 지정, CSS 잡는데 좀 애를 먹었습니다. (전부 다..?)
close #7
> Design: 공통 컴포넌트 체크박스 제작

- src/components/buttons/DateChangeButton/index.tsx
- src/components/buttons/DateChangeButton/styles.ts
- src/components/navBar/upperNavBar/index.tsx
- src/components/priceArea/styles.ts
- src/pages/sell/components/InfoBox.tsx
- src/pages/sell/confirm.tsx
- src/pages/sell/detail.tsx
- src/pages/sell/result.tsx
- src/pages/sell/styles/confirm.ts
- src/pages/sell/styles/register.ts
- src/pages/sell/styles/result.ts
- src/routes/router.tsx
#55 
- 양도 확인 페이지 2p (양도관련 화면구현은 완료!)
- upperNav type="close" 와 type="back" 동일한 동작으로 통일
- DateChangeButton disabled 속성 추가
close #55
> Design: 양도 확인페이지 2p

- .gitignore
- src/pages/notice/constants.ts
- src/pages/notice/index.tsx
- src/pages/notice/styles.ts
- src/pages/notice/type.ts
- src/pages/products/components/ProductList/index.tsx
- src/pages/products/index.tsx
#87 
~~별점 및 후기 페이지~~
- 이상 없음, API 연결 필요
- 상단 네비게이션 바 우측 중앙 정렬이 안 되는데 요거 나머지 머지되고 나면 해결할 예정입니다!
- 전체 선택 시 전체 삭제 모달이 나오게 바꿔야 하는데,, API 연결 하면서 완성할 예정입니다.
close #
> Feat: 알림 페이지 애니메이션 및 모달 추가

- src/pages/home/api/accumulate.ts
- src/pages/products/api/products.ts
> Fix: API 주소 수정

- src/pages/home/api/accumulate.ts
> Fix: accumulate api 헤더 제거

- src/apis/instance.ts
- src/pages/login/EmailLogin.tsx
- 로그인에는 v1이 없어서 로그인 전용 instance를 만들었습니다. 나중에 담당자분이 커스텀하시면 될 것 같습니다!
close #
> Refactor: 로그인 용 instance 제작

- src/apis/instance.ts
- src/firebase-messaging-sw.ts
- src/main.tsx
- src/pages/home/api/putFCMToken.ts
- src/pages/home/hooks/useFCMToken.ts
- src/pages/home/index.tsx
- src/pages/myPage/apis/postLogout.ts
- src/pages/myPage/apis/putChangeNickname.ts
- src/pages/myPage/utils/formatNumberWithCommas.ts
- src/pages/signIn/apis/putChangePassword.ts
- src/pages/signIn/apis/putPhoneNumber.ts
- tsconfig.json
- FCM 토큰 업데이트 API 연동
- FCM 토큰 api 호출 url 수정
- 토큰 요청 로직 수정
- 로그인 여부 판단 로직 수정
- formatNumberWithCommas 함수 로직 수정
- 멤버 API URL 수정
굳!
없습당당당~~
close #140
> Feat: FCM 토큰 업데이트 API 연동

- src/pages/home/components/Header/style.ts
- src/pages/home/components/SearchInput/style.ts
#148 
- 반영 완!
- 더 깔끔해짐!
close #148
> Feat: 범식님 디자인 요구사항 반영

- src/pages/charge/account.tsx
- src/pages/charge/confirm.tsx
- src/pages/charge/index.tsx
- src/pages/charge/intro.tsx
- src/pages/charge/list.tsx
- src/pages/charge/success.tsx
- src/pages/purchase/index.tsx
- src/pages/sell/index.tsx
#149 
- img import 경로 수정 및 버튼 활성화 추가
close #149
> Fix: img import 경로 수정 및 버튼 활성화 추가

- src/pages/chat/ChatRoom.tsx
- src/pages/chat/components/chatText/index.tsx
- src/pages/chat/hooks/useChatRooms.ts
- src/pages/chat/hooks/useSocket.ts
- src/pages/chat/index.tsx
- src/pages/productDetail/components/NegoButton/index.tsx
> Fix: 채팅 관련 데이터 경로 수정

- src/pages/notice/components/NoNotice.tsx
- src/pages/notice/components/styles.ts
- src/pages/notice/index.tsx
> Feat: 알림 없을 때 보여줄 페이지 제작

- src/pages/myPage/apis/postLogout.ts
- src/pages/myPage/index.tsx
- src/pages/purchase/index.tsx
#158 
- 핸드폰번호 포매팅 함수 추가
- 로그아웃 api url 수정
- 판매, 구매내역 alertButton 삭제
- 단순 에러 수정이라 생략하겠습니다.
- 굳굳
- 마이페이지 알림 버튼 하드코딩된거 변경할 예정입니다!
close #
> Fix: 마이페이지, 구매페이지 QA

- src/pages/charge/account.tsx
- src/pages/charge/apis/charge.ts
- src/pages/charge/apis/register.ts
- src/pages/charge/hooks/usePaymentList.ts
- src/pages/charge/hooks/usePaymentQuery.ts
- src/pages/charge/hooks/useRegisterPayment.ts
- src/pages/charge/index.tsx
- src/pages/charge/intro.tsx
- src/pages/charge/list.tsx
- src/pages/charge/styles/list.ts
- src/pages/charge/success.tsx
- src/pages/sell/index.tsx
- src/pages/sell/types/sellListData.ts
- src/pages/signIn/components/signInFourth/SignInFourth.tsx
#157 
- 페이내역 무한스크롤 및 에러메세지 모달 띄우기
이상 없음
close #157
> Feat: 페이내역 무한스크롤 및 에러메세지 모달 띄우기

- src/apis/instance.ts
- src/pages/myPage/apis/getSellTransactionHistory.ts
- src/pages/myPage/index.tsx
- src/pages/purchase/index.tsx
#167 
- 마이페이지 아이콘 추가
- 결제금액 50000원 미만시 할부기간 선택 불가
- 승인 거절 시 페이지 새로고침 로직 추가
- 야놀자페이 결제로직 수정
- 로그아웃시 로직 추가
- 판매내역서 api url 수정
생략
- 결제금액 50000원 미만시 테스트 필요
- 로그아웃 2번되는 현상 테스트 필요
close #167
> Fix: 마이페이지, 구매페이지 3차 QA

- src/pages/chat/components/chatRoomBanner/index.tsx
- src/pages/login/index.tsx
> Fix: 카카오 소셜로그인 링크 수정

- src/components/buttons/CardSectionButton/index.tsx
- src/main.tsx
- src/pages/myPage/hooks/useBalance.ts
- src/pages/myPage/hooks/useProfileDetail.ts
- src/pages/myPage/index.tsx
- src/pages/notice/components/styles.ts
- src/pages/notice/index.tsx
- src/pages/notice/queries.ts
- src/pages/products/api/products.ts
- src/pages/products/components/ProductList/index.tsx
- src/pages/search/components/BottomActions/index.tsx
- src/pages/search/stores/guestStore.ts
- src/pages/sell/apis/getSellList.ts
- src/pages/sell/hooks/useGetSellList.ts
- src/pages/sell/index.tsx
- src/styles/globalStyles.ts
#172 
- 날짜 검색 가능
- 알림 삭제 시 바로 반영
- 알림 없을 때 로고 중앙으로 오게 수정
- 이상 무
close #172
> Fix: 검색 필터 체크인 체크아웃 추가 & 알림 삭제 시 refetch

- src/components/modal/index.tsx
- src/pages/myPage/index.tsx
- src/pages/products/components/KakaoMap/index.tsx
- src/pages/search/components/BottomActions/index.tsx
> Fix: 지도, 버튼 수정 및 쿠키에서 isLoggedIn 제거

- src/components/card/ColumnCard/index.tsx
- src/pages/home/components/CategoryProduct/index.tsx
- src/pages/home/components/SpecialServices/index.tsx
- src/pages/home/components/SubServices/index.tsx
- src/pages/home/components/SubServices/styles.ts
- src/pages/products/api/products.ts
- src/pages/products/api/queries.ts
- src/pages/products/components/KakaoMap/ProductsMarkers.tsx
- src/pages/products/components/KakaoMap/Research.tsx
- src/pages/products/components/KakaoMap/index.tsx
- src/pages/products/components/KakaoMap/styles.ts
- src/pages/products/components/ProductList/index.tsx
- src/pages/products/hooks/usePreviousParams.ts
- src/pages/search/components/BottomActions/index.tsx
- src/utils/formatDateTo.ts
#181 
- 검색 탭 키워드 입력 시 버튼 활성화
- 판매 완료된 숙소 홈에서 제거
- 검색 리스트 변경 시 지도에 반영
- 최초 검색 리스트 size 변경
- 다음에 할 거: 선택된 숙소 전역으로 관리
close #181
> Fix: 지도, 검색, 홈 QA 수정

- src/apis/instance.ts
- src/components/checkEmail/index.tsx
- src/pages/myPage/index.tsx
- src/pages/signIn/apis/postCode.ts
- src/pages/signIn/apis/postEmailAuth.ts
- src/pages/signIn/apis/postEmailDuplicateCheck.ts
- src/pages/signIn/hooks/useCodeCheck.ts
- src/pages/signIn/hooks/useEmailAuth.ts
- src/pages/signIn/hooks/useEmailDuplicateCheck.ts
182
- 400에러 시에 refetch하도록 instance 및 authInstance 수정
- 이메일 인증 로직 변경
- API 추가 연동
- 비밀 번호 재설정 페이지 & 회원가입 페이지에서 API 분리
close #182
> [Feat]: instance.ts 수정 및 이메일 인증 로직 변경

- src/components/input/TextInput/styles.ts
- src/pages/productDetail/components/DetailInfo/index.tsx
- src/pages/productDetail/components/DetailInfo/style.ts
- src/pages/productDetail/components/NegoButton/index.tsx
#186 
- 로그인 없이 결제하기 누를 시 로그인 페이지로 이동
- 로그인 아닐 시 상품 정보 수정 버튼 안 보이게 변경 (이건 원래 처리되어 있었는데 isLoggedIn도 추가)
- 비회원 접근 시 에러는 일시적으로 쿠키가 섞이면서 생긴 현상인 듯
close #186
> Fix: 상품 상세 로그인 분기 처리 및 세부 디자인 조정

- src/components/card/ListCard/index.tsx
- src/components/card/ListCard/styles.ts
- src/components/input/Checkbox/AllConsentCheckbox.tsx
- src/firebase-messaging-sw.ts
- src/pages/home/index.tsx
- src/pages/myPage/components/Info/index.tsx
- src/pages/myPage/profile.tsx
- src/pages/myPage/styles/history.styles.ts
- src/pages/myPage/styles/profile.styles.ts
- src/pages/notice/queries.ts
- src/pages/purchase/index.tsx
- src/pages/purchase/styles/styles.ts
- src/routes/router.tsx
- src/utils/indexDB.ts
#179 
- 필수약관 동의 클릭시 이용자 정보로 올라가는 현상 수정
- 프로필 이미지 오류 해결
- 회원 아이디 표기 오류 해결
- isLocal 삭제
- 거래내역서 수수료 소수점 표시
- "야놀자에서 거래내역 확인" 클릭시 로직 추가
- 결제페이지 이미지 사이즈 조절
- 리스트카드 쉐도우 삭제
- FCM 토큰 저장 로직 indexDB로 변경
- 생략
- 이상 없습니당
- FCM 토큰 저장 로직 indexDB로 변경은 모바일에서 테스트 후 이상 있으면 롤백할게요!
close #179
> Fix: 마이페이지, 구매페이지 5차 QA

- src/components/priceArea/index.tsx
- src/pages/charge/apis/charge.ts
- src/pages/charge/index.tsx
- src/pages/charge/list.tsx
- src/pages/myPage/salesHistory.tsx
- src/pages/sell/components/AutoCancelOption.tsx
- src/pages/sell/confirm.tsx
- src/pages/sell/correct.tsx
- src/pages/sell/register.tsx
- src/utils/calcCancelFee.ts
#194 
- 양도/페이 3차 QA 수정
close #194
> Fix: 양도/페이 3차 QA 수정

- src/components/navBar/bottomNavBar/NavButton.tsx
- src/components/navBar/bottomNavBar/index.tsx
비로그인시 불필요한 api 호출 차단
close #201
> HotFix: 비로그인시 불필요한 api 호출 차단

- src/apis/instance.ts
- src/components/priceArea/index.tsx
- src/pages/charge/hooks/useRegisterPayment.ts
- src/pages/charge/pay.tsx
#204 
-PriceArea If문 수정
close #204
> Fix: PriceArea If문 수정

- src/components/certification/index.tsx
- src/pages/purchase/reservationComplete.tsx
- src/styles/globalStyles.ts
#196 
- 스크롤바 스타일링
- 휴대폰 인증 롤백
- tradeId null인 경우 에러 해결
- 생략
- 배포사이트에서 테스트 예정입니다.
close #196
> Fix: 마이페이지, 구매페이지 7차 QA

- src/pages/search/components/SearchHistory/index.tsx
> Fix: 검색 히스토리 수정

- src/pages/productDetail/components/NegoButton/index.tsx
#218 
- 비로그인시 상세페이지 접근 오류 해결
close #218
> Fix: 비로그인시 상세페이지 접근 오류 해결

- src/components/card/RecentlyRowCard/index.tsx
- src/pages/home/components/RecentlyProduct/index.tsx
- src/pages/home/index.tsx
- src/pages/home/stores/recentStore.ts
- src/pages/home/types/recent.ts
- src/pages/products/components/ProductCard/index.tsx
#220 
- 홈 최근 본 상품!
- 최근 본 상품이 없을땐 보이지 않음
- 최근 본 5개의 상품만 담김!
- 최근 본 상품이 존재할 때
- 최근 본 상품이 존재하지 않을때
close #220
> Feat: 홈 - 최근 본 상품

- src/components/modal/index.tsx
- src/pages/home/components/Header/index.tsx
- vite.config.ts
- 비로그인 시 알림 뱃지 제거
- 모달 버튼 색깔 위치 변경
- 빌드 시 콘솔 로그 제거
close #
> Fix: 비로그인 시 알림뱃지 숫자 제거 & 모달 버튼 색깔 변경

- src/pages/products/components/ProductCard/ProductCardForMap.tsx
- src/pages/products/components/ProductCard/style.ts
> Feat: 지도 카드에서 상세 정보로 갈 수 있게 링크 추가

- src/apis/instance.ts
- src/mocks/handlers.ts
- src/pages/charge/password.tsx
- src/pages/charge/pay.tsx
- src/pages/chat/components/chatText/index.tsx
- src/pages/productDetail/api/detail.ts
- src/pages/sell/components/NegoOption.tsx
- src/pages/sell/index.tsx
> Fix: 야놀자 결제 플로우 수정

- package.json
- src/pages/myPage/index.tsx
- src/pages/purchase/index.tsx
- src/pages/purchase/reservationComplete.tsx
#224 
- 잔액 부족하지 않을 경우 purchaseInfo 미리 set
- 결제 완료 정보 전송 방식 localstorage에서 querystring으로 변경 및 redirect url 변경
- 예약자 정보 펼쳐져있드록 수정
- 마이페이지 뒤로가기 로직 오류 수정
- 생략
- 예인누나거랑 머지 후 테스트 예정!!
`npm i` 해줘야해용!!!!!
close #224
> Fix: 마이페이지, 구매페이지 9차 QA

- src/pages/login/hooks/useLogin.ts
231
존재하지 않는 회원 로그인 시 400에러 발생하는 경우 처리
close #231
> Fix: 존재하지 않는 회원 로그인 시 에러 처리

- src/pages/chat/components/chatInput/index.tsx
- src/pages/chat/styles/styles.ts
> [Fix]: 채팅방 목록 가려지는 이슈 해결 및 Enter키 동작 추가

- src/pages/charge/account.tsx
- src/pages/charge/success.tsx
- src/pages/sell/confirm.tsx
#237 
- 워딩 및 버튼삭제요청
close #237
> Fix: 워딩 및 버튼삭제요청

- src/components/navBar/bottomNavBar/styles.ts
> Fix: ios 11 용 padding bottom 추가

- src/styles/fonts.ts
> Fix: Pretendard 폰트 추가

- src/main.css
> Fix: safe area 추가

- src/components/card/ListCard/index.tsx
- src/components/modal/index.tsx
> Fix: 버튼 반대색상 추가

- src/components/card/ListCard/index.tsx
> Fix: 모달 재수정
